---
- name: Install pgwatch2
  yum:
    name: "{{ pgwatch2_rpm_url }}"
    disable_gpg_check: "true"

# - name: Install pgwatch2
#   apt:
#     deb: "{{ pgwatch2_deb_url }}"

- name: Copy pgwatch2 config
  template:
    src: instances.j2
    dest: /etc/pgwatch2/config/instances.yaml
    owner: root
    group: root
    mode: "0640"

- name: Deploy systemd unit
  template:
    src: pgwatch2.service
    dest: /etc/systemd/system/pgwatch2.service
    owner: root
    group: root
    mode: "0644"
  notify: restart pgwatch2
