---
galaxy_info:
  author: Fachschaft Informatik, TU Dortmund
  description: Install and configure pgwatch2
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
dependencies: []
