---
# tasks file for wal-g
- name: Fail for unsupported architecture
  fail:
    msg: "Can't install wal-g: unsupported arch ({{ ansible_architecture }})."
  when: ansible_architecture != "x86_64"

- name: create wal-g folder
  become: yes
  become_user: "{{ walg_owner }}"
  file:
    state: directory
    dest: "{{ walg_bin_path }}"
    owner: "{{ walg_owner }}"
    mode: "0755"

- name: Download wal-g
  become: yes
  become_user: "{{ walg_owner }}"
  get_url:
    url: "{{ walg_exe_url }}"
    dest: "{{ walg_bin_path }}"
    mode: "0755"

- name: Install wal-g binary
  become: yes
  become_user: "{{ walg_owner }}"
  file:
    state: link
    src: "{{ walg_bin_path }}/{{ walg_exe_name }}"
    dest: "/usr/local/bin/wal-g"
    force: yes
