---
- name: Halt
  vars:
    _cluster_name: "{{ cluster_name | default('cluster1') }}"
  hosts:
    - "{{ _cluster_name }}-*"
  tasks:
    - name: Exit
      ansible.builtin.assert:
        that: _cluster_name | length > 5

- name: Deploy minimal
  vars:
    _cluster_name: "{{ cluster_name | default('cluster1') }}"
  hosts:
    - "{{ _cluster_name }}-*"
  become: true
  gather_facts: true
  roles:
    - role: linux
      tags:
        - linux
        - packages
    - role: chainsmith
      tags:
        - chainsmith
        - certificates
        - certs
    - role: firewall
      tags:
        - firewall
        - firewalld
    - role: etcd
      tags:
        - etcd
    - role: walg
      tags:
        - walg
    - role: stolon
      tags:
        - stolon
        - postgres
        - postgresql
        - pg
    # - role: avchecker
    #   tags:
    #     - linux
    # - role: pgquartz
    #   tags:
    #     - linux
