---
- name: Halt
  vars:
    _cluster_name: "{{ cluster_name | default('cluster1') }}"
  hosts:
    - "{{ _cluster_name }}-*"
  tasks:
    - name: Exit
      ansible.builtin.assert:
        that: _cluster_name | length > 5

- name: Deploy minimal
  vars:
    _cluster_name: "{{ cluster_name | default('cluster1') }}"
  hosts:
    - "{{ _cluster_name }}-*"
  become: true
  gather_facts: true
  roles:
    - role: pgvillage.linux
      tags:
        - linux
        - packages
    - role: pgvillage.chainsmith
      tags:
        - chainsmith
        - certificates
        - certs
    - role: pgvillage.firewall
      tags:
        - firewall
        - firewalld
    - role: pgvillage.etcd
      tags:
        - etcd
    - role: pgvillage.walg
      tags:
        - walg
    - role: pgvillage.stolon
      tags:
        - stolon
        - postgres
        - postgresql
        - pg
    # - role: pgvillage.avchecker
    #   tags:
    #     - linux
    # - role: pgvillage.pgquartz
    #   tags:
    #     - linux
