---
- name: Test
  hosts:
    - backup
  become: true
  gather_facts: false
  tasks:
    - name: Check the status of the stanza
      ansible.builtin.command: ls /
      register: stanza_check
      changed_when: false
    - name: Debug
      ansible.builtin.debug:
        var: stanza_check
