---
- name: Converge
  hosts: all
  tasks:
    - name: Install some dependencies for the role tests
      package:
        name:
          - sudo
        update_cache: true
        state: present

    - name: Install epel on CentOS
      package:
        name:
          - epel-release
        state: present
      when:
        - "ansible_distribution in ['CentOS']"

    - name: Install postgres
      package:
        name:
          - postgresql-server
        state: present
      when:
        - "ansible_distribution in ['CentOS']"

    - name: Init postgres DB (CentOS)
      command: "postgresql-setup initdb"
      when:
        - "ansible_distribution in ['CentOS']"
      become: true
      become_user: postgres

    - name: Install postgres
      package:
        name:
          - postgresql-9.6
        state: present
      when:
        - "ansible_distribution in ['Debian']"
        - "ansible_distribution_major_version|int == 9"

    - name: Install postgres
      package:
        name:
          - postgresql-11
        state: present
      when:
        - "ansible_distribution in ['Debian']"
        - "ansible_distribution_major_version|int == 10"

    - name: Start postgresql
      service:
        name: postgresql
        state: started
