---
- name: Install rpm key for pgdg repo
  rpm_key:
    key: "{{ __pgbackrest_postgresql_rhel_repo_rpm_key }}"
    state: present
  when:
    - "__pgbackrest_postgresql_rhel_repo_rpm_key is not none"
    - "__pgbackrest_postgresql_rhel_repo_package is not none"

- name: Install pgdg repo
  package:
    name: "{{ __pgbackrest_postgresql_rhel_repo_package }}"
    state: present
  when:
    - "__pgbackrest_postgresql_rhel_repo_package is not none"

- name: Install dependency packages
  package:
    name: "{{ __pgbackrest_packages }}"
    state: present
