---
- include_tasks: "install_local.yml"
  when: install_from_satellite == "false"

- include_tasks: "install_from_satellite.yml"
  when: install_from_satellite == "true"

- include_tasks: "config.yml"
