---
subject:
  C:  NL/postalCode=3721 MA
  ST: Utrecht
  L:  Bilthoven/street=Antonie v Leeuwenhoekln 9
  O:  Rijksinstituut voor Volksgezondheid en Milieu (RIVM)
  OU: Postgres bouwblok
  CN: postgres

#tmpdir: /tmp/certs/postgres

intermediates:
  - name: server
    keyUsages:
      - keyEncipherment
      - dataEncipherment
      - digitalSignature
    extendedKeyUsages:
      - serverAuth
    servers: {}
# You can set servers directly
#      myserver1:
#        - 192.168.13.14
# You can read servers from an environment
  - name: client
    clients:
      - postgres
      - application
      - avchecker
      - pgquartz
      - pgfga
    keyUsages:
      - keyEncipherment
      - dataEncipherment
      - digitalSignature
    extendedKeyUsages:
      - clientAuth
