- unique_name: {{ pgwatch2_instance_name }}
  dbtype: postgres-continuous-discovery
  host: {{ pgwatch2_db_host }}
  port: {{ pgwatch2_db_port }}
  user: {{ pgwatch2_db_user }}
  password: {{ pgwatch2_db_pass }}
  is_superuser: true
  sslmode: disable
  preset_metrics: exhaustive
  is_enabled: true
  group: default
