---

- name: Compose the Minio client download url
  set_fact:
    _minio_client_download_url: "https://dl.minio.io/client/mc/release/linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/mc"

- name: "Get the Minio client checksum for {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }} architecture"
  set_fact:
    _minio_client_checksum: "{{ lookup('url', _minio_client_download_url + '.sha256sum').split(' ')[0] }}"

- name: Download the Minio client
  get_url:
    url: "{{ _minio_client_download_url }}"
    dest: "{{ minio_client_bin }}"
    owner: "root"
    group: "root"
    mode: 0755
    checksum: "sha256:{{ _minio_client_checksum }}"
  when: minio_client_package_name is not defined
  register: _download_client
  until: _download_client is succeeded
  retries: 5
  delay: 2

- name: Install client package
  package:
    name: "{{ minio_client_package_name }}"
    state: present
  when: minio_client_package_name is defined

