---
# defaults file for postgresql

postgresql_version: 12
postgresql_packages:
  - { name: "postgresql{{ postgresql_version|replace('.','') }}",           state: "present" }
  - { name: "postgresql{{ postgresql_version|replace('.','') }}-server",    state: "present" }
  - { name: "postgresql{{ postgresql_version|replace('.','') }}-contrib",   state: "present" }
  - { name: "postgresql{{ postgresql_version|replace('.','') }}-devel",     state: "present" }
  - { name: "postgresql{{ postgresql_version|replace('.','') }}-plpython3", state: "present" }

postgresql_rhsm_product: "Postgresql{{ postgresql_version }}_8Server"

postgresql_base_dir: "/var/lib/pgsql/{{ postgresql_version }}"
postgresql_datadir: "{{ postgresql_base_dir }}/data"
postgresql_pgconf: "{{ postgresql_datadir }}/postgresql.conf"

postgresql_user: postgres
postgresql_group: "{{ postgresql_user }}"
