---
- name: Set installable packages list
  set_fact:
    __pgbackrest_packages: >-
      {%- if pgbackrest_packages is not none -%}
        {{ pgbackrest_packages }}
      {%- elif (
           (ansible_distribution|lower in _pgbackrest_packages) and
           (ansible_distribution_major_version|string in _pgbackrest_packages[ansible_distribution|lower])
         ) -%}
         {{ _pgbackrest_packages[ansible_distribution|lower][ansible_distribution_major_version|string] }}
      {%- elif (
           (ansible_distribution|lower in _pgbackrest_packages) and
           (ansible_distribution_major_version|int in _pgbackrest_packages[ansible_distribution|lower])
         ) -%}
         {{ _pgbackrest_packages[ansible_distribution|lower][ansible_distribution_major_version|int] }}
      {%- elif (ansible_distribution|lower in _pgbackrest_packages) -%}
         {{ _pgbackrest_packages[ansible_distribution|lower] }}
      {%- else %}
        {{ none }}
      {%- endif -%}

- name: Determine the postgresql conf file path
  set_fact:
    __pgbackrest_postgresql_conf_path: >-
      {%- if pgbackrest_postgresql_conf_path is not none -%}
        {{ pgbackrest_postgresql_conf_path }}
      {%- elif (
           (ansible_distribution|lower in _pgbackrest_postgresql_conf_path) and
           (_pgbackrest_postgresql_conf_path[ansible_distribution|lower] is mapping) and
           (ansible_distribution_major_version|string in _pgbackrest_postgresql_conf_path[ansible_distribution|lower])
         ) -%}
         {{ _pgbackrest_postgresql_conf_path[ansible_distribution|lower][ansible_distribution_major_version|string] }}
      {%- elif (
           (ansible_distribution|lower in _pgbackrest_postgresql_conf_path) and
           (_pgbackrest_postgresql_conf_path[ansible_distribution|lower] is mapping) and
           (ansible_distribution_major_version|int in _pgbackrest_postgresql_conf_path[ansible_distribution|lower])
         ) -%}
         {{ _pgbackrest_postgresql_conf_path[ansible_distribution|lower][ansible_distribution_major_version|int] }}
      {%- elif (ansible_distribution|lower in _pgbackrest_postgresql_conf_path) -%}
         {{ _pgbackrest_postgresql_conf_path[ansible_distribution|lower] }}
      {%- endif -%}


- name: Set the RHEL repo package
  set_fact:
    __pgbackrest_postgresql_rhel_repo_package: >-
      {%- if pgbackrest_postgresql_rhel_repo_package is not none -%}
        {{ pgbackrest_postgresql_rhel_repo_package }}
      {%- elif (
           (ansible_distribution|lower in _pgbackrest_postgresql_rhel_repo_package) and
           (_pgbackrest_postgresql_rhel_repo_package[ansible_distribution|lower] is mapping) and
           (ansible_distribution_major_version|string in _pgbackrest_postgresql_rhel_repo_package[ansible_distribution|lower])
         ) -%}
         {{ _pgbackrest_postgresql_rhel_repo_package[ansible_distribution|lower][ansible_distribution_major_version|string] }}
      {%- elif (
           (ansible_distribution|lower in _pgbackrest_postgresql_rhel_repo_package) and
           (_pgbackrest_postgresql_rhel_repo_package[ansible_distribution|lower] is mapping) and
           (ansible_distribution_major_version|int in _pgbackrest_postgresql_rhel_repo_package[ansible_distribution|lower])
         ) -%}
         {{ _pgbackrest_postgresql_rhel_repo_package[ansible_distribution|lower][ansible_distribution_major_version|int] }}
      {%- elif (ansible_distribution|lower in _pgbackrest_postgresql_rhel_repo_package) -%}
         {{ _pgbackrest_postgresql_rhel_repo_package[ansible_distribution|lower] }}
      {%- else %}
        {{ none }}
      {%- endif -%}

- name: Set the RHEL repo package RPM key var
  set_fact:
    __pgbackrest_postgresql_rhel_repo_rpm_key: >-
      {%- if pgbackrest_postgresql_rhel_repo_rpm_key is not none -%}
        {{ pgbackrest_postgresql_rhel_repo_rpm_key }}
      {%- elif (
           (ansible_distribution|lower in _pgbackrest_postgresql_rhel_repo_rpm_key) and
           (_pgbackrest_postgresql_rhel_repo_rpm_key[ansible_distribution|lower] is mapping) and
           (ansible_distribution_major_version|string in _pgbackrest_postgresql_rhel_repo_rpm_key[ansible_distribution|lower])
         ) -%}
         {{ _pgbackrest_postgresql_rhel_repo_rpm_key[ansible_distribution|lower][ansible_distribution_major_version|string] }}
      {%- elif (
           (ansible_distribution|lower in _pgbackrest_postgresql_rhel_repo_rpm_key) and
           (_pgbackrest_postgresql_rhel_repo_rpm_key[ansible_distribution|lower] is mapping) and
           (ansible_distribution_major_version|int in _pgbackrest_postgresql_rhel_repo_rpm_key[ansible_distribution|lower])
         ) -%}
         {{ _pgbackrest_postgresql_rhel_repo_rpm_key[ansible_distribution|lower][ansible_distribution_major_version|int] }}
      {%- elif (ansible_distribution|lower in _pgbackrest_postgresql_rhel_repo_rpm_key) -%}
         {{ _pgbackrest_postgresql_rhel_repo_rpm_key[ansible_distribution|lower] }}
      {%- endif -%}
